services:
  brew-buddy-db:
    container_name: brew-buddy-db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brew-buddy
    ports:
      - "5433:5432"
    volumes:
      - bbdata:/var/lib/postgresql/data

  brew-buddy-app:
    build: .
    container_name: brew-buddy-app
    restart: unless-stopped
    depends_on:
      - brew-buddy-db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@brew-buddy-db:5432/brew-buddy?schema=public
    ports:
      - "3100:3000"

volumes:
  bbdata:
