/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as BatchesIndexRouteImport } from './routes/batches/index'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as IngredientsNewRouteImport } from './routes/ingredients/new'
import { Route as BatchesNewRouteImport } from './routes/batches/new'
import { Route as BatchesIdIndexRouteImport } from './routes/batches/$id/index'
import { Route as RecipesIdEditRouteImport } from './routes/recipes/$id/edit'
import { Route as IngredientsIdEditRouteImport } from './routes/ingredients/$id/edit'
import { Route as BatchesIdLabelRouteImport } from './routes/batches/$id/label'
import { Route as BatchesIdEditRouteImport } from './routes/batches/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsNewRoute = IngredientsNewRouteImport.update({
  id: '/ingredients/new',
  path: '/ingredients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesNewRoute = BatchesNewRouteImport.update({
  id: '/batches/new',
  path: '/batches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIdIndexRoute = BatchesIdIndexRouteImport.update({
  id: '/batches/$id/',
  path: '/batches/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdEditRoute = RecipesIdEditRouteImport.update({
  id: '/recipes/$id/edit',
  path: '/recipes/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIdEditRoute = IngredientsIdEditRouteImport.update({
  id: '/ingredients/$id/edit',
  path: '/ingredients/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIdLabelRoute = BatchesIdLabelRouteImport.update({
  id: '/batches/$id/label',
  path: '/batches/$id/label',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIdEditRoute = BatchesIdEditRouteImport.update({
  id: '/batches/$id/edit',
  path: '/batches/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches/new': typeof BatchesNewRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/batches/': typeof BatchesIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/batches/$id/edit': typeof BatchesIdEditRoute
  '/batches/$id/label': typeof BatchesIdLabelRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/batches/$id/': typeof BatchesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches/new': typeof BatchesNewRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/batches': typeof BatchesIndexRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/batches/$id/edit': typeof BatchesIdEditRoute
  '/batches/$id/label': typeof BatchesIdLabelRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/batches/$id': typeof BatchesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches/new': typeof BatchesNewRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/batches/': typeof BatchesIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/batches/$id/edit': typeof BatchesIdEditRoute
  '/batches/$id/label': typeof BatchesIdLabelRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/batches/$id/': typeof BatchesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batches/new'
    | '/ingredients/new'
    | '/recipes/new'
    | '/batches/'
    | '/ingredients/'
    | '/recipes/'
    | '/batches/$id/edit'
    | '/batches/$id/label'
    | '/ingredients/$id/edit'
    | '/recipes/$id/edit'
    | '/batches/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batches/new'
    | '/ingredients/new'
    | '/recipes/new'
    | '/batches'
    | '/ingredients'
    | '/recipes'
    | '/batches/$id/edit'
    | '/batches/$id/label'
    | '/ingredients/$id/edit'
    | '/recipes/$id/edit'
    | '/batches/$id'
  id:
    | '__root__'
    | '/'
    | '/batches/new'
    | '/ingredients/new'
    | '/recipes/new'
    | '/batches/'
    | '/ingredients/'
    | '/recipes/'
    | '/batches/$id/edit'
    | '/batches/$id/label'
    | '/ingredients/$id/edit'
    | '/recipes/$id/edit'
    | '/batches/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesNewRoute: typeof BatchesNewRoute
  IngredientsNewRoute: typeof IngredientsNewRoute
  RecipesNewRoute: typeof RecipesNewRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  BatchesIdEditRoute: typeof BatchesIdEditRoute
  BatchesIdLabelRoute: typeof BatchesIdLabelRoute
  IngredientsIdEditRoute: typeof IngredientsIdEditRoute
  RecipesIdEditRoute: typeof RecipesIdEditRoute
  BatchesIdIndexRoute: typeof BatchesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/': {
      id: '/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/new': {
      id: '/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof IngredientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/new': {
      id: '/batches/new'
      path: '/batches/new'
      fullPath: '/batches/new'
      preLoaderRoute: typeof BatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$id/': {
      id: '/batches/$id/'
      path: '/batches/$id'
      fullPath: '/batches/$id/'
      preLoaderRoute: typeof BatchesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/edit': {
      id: '/recipes/$id/edit'
      path: '/recipes/$id/edit'
      fullPath: '/recipes/$id/edit'
      preLoaderRoute: typeof RecipesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$id/edit': {
      id: '/ingredients/$id/edit'
      path: '/ingredients/$id/edit'
      fullPath: '/ingredients/$id/edit'
      preLoaderRoute: typeof IngredientsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$id/label': {
      id: '/batches/$id/label'
      path: '/batches/$id/label'
      fullPath: '/batches/$id/label'
      preLoaderRoute: typeof BatchesIdLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$id/edit': {
      id: '/batches/$id/edit'
      path: '/batches/$id/edit'
      fullPath: '/batches/$id/edit'
      preLoaderRoute: typeof BatchesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesNewRoute: BatchesNewRoute,
  IngredientsNewRoute: IngredientsNewRoute,
  RecipesNewRoute: RecipesNewRoute,
  BatchesIndexRoute: BatchesIndexRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  BatchesIdEditRoute: BatchesIdEditRoute,
  BatchesIdLabelRoute: BatchesIdLabelRoute,
  IngredientsIdEditRoute: IngredientsIdEditRoute,
  RecipesIdEditRoute: RecipesIdEditRoute,
  BatchesIdIndexRoute: BatchesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
