/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as IngredientsNewRouteImport } from './routes/ingredients/new'
import { Route as RecipesIdEditRouteImport } from './routes/recipes/$id/edit'
import { Route as IngredientsIdEditRouteImport } from './routes/ingredients/$id/edit'

const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsNewRoute = IngredientsNewRouteImport.update({
  id: '/ingredients/new',
  path: '/ingredients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdEditRoute = RecipesIdEditRouteImport.update({
  id: '/recipes/$id/edit',
  path: '/recipes/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIdEditRoute = IngredientsIdEditRouteImport.update({
  id: '/ingredients/$id/edit',
  path: '/ingredients/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/ingredients/$id/edit': typeof IngredientsIdEditRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batches'
    | '/ingredients/new'
    | '/recipes/new'
    | '/ingredients/'
    | '/recipes/'
    | '/ingredients/$id/edit'
    | '/recipes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batches'
    | '/ingredients/new'
    | '/recipes/new'
    | '/ingredients'
    | '/recipes'
    | '/ingredients/$id/edit'
    | '/recipes/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/batches'
    | '/ingredients/new'
    | '/recipes/new'
    | '/ingredients/'
    | '/recipes/'
    | '/ingredients/$id/edit'
    | '/recipes/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesRoute: typeof BatchesRoute
  IngredientsNewRoute: typeof IngredientsNewRoute
  RecipesNewRoute: typeof RecipesNewRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  IngredientsIdEditRoute: typeof IngredientsIdEditRoute
  RecipesIdEditRoute: typeof RecipesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/new': {
      id: '/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof IngredientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/edit': {
      id: '/recipes/$id/edit'
      path: '/recipes/$id/edit'
      fullPath: '/recipes/$id/edit'
      preLoaderRoute: typeof RecipesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$id/edit': {
      id: '/ingredients/$id/edit'
      path: '/ingredients/$id/edit'
      fullPath: '/ingredients/$id/edit'
      preLoaderRoute: typeof IngredientsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesRoute: BatchesRoute,
  IngredientsNewRoute: IngredientsNewRoute,
  RecipesNewRoute: RecipesNewRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  IngredientsIdEditRoute: IngredientsIdEditRoute,
  RecipesIdEditRoute: RecipesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
